{
 "title": "IP Reserve Delay Release",
 "description": "IP Reserved Delay Release",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "datasource", "query": "Prometheus" }
  ]
 },
 "panels": [
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocatable Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ip_reserve_count_max{cluster=\"$cluster\"})",
     "legendFormat": "{{persistentvolumeclaim=}}"
    }
   ]
  },
  {
   "title": "Reserved Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ip_reserve_count{cluster=\"$cluster\"})",
     "legendFormat": "{{persistentvolumeclaim=}}"
    }
   ]
  },
  {
   "title": "Reserved IP Percent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ip_reserve_count{cluster=\"$cluster\"})/max(ip_reserve_count_max{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Reserved IP Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "max(ip_reserve_count_max{cluster=\"$cluster\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "max(ip_reserve_count{cluster=\"$cluster\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  { "title": "Reserved IP Kept Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Reserved IP Info",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ip_reserve_kept_time{pod_ip_owner_namespace=~\"$namespace\", pod_ip_owner_node_name=~\"$node\"}"
    }
   ]
  }
 ]
}