resources:
- manifests.yaml
- service.yaml

patchesStrategicMerge:
- namespace_selector_patch.yaml

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  path: eviction_rules_patch.yaml

configurations:
- kustomizeconfig.yaml
