apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: pod.ip.io
    namespaceSelector:
      matchExpressions:
        - key: ip-reserve
          operator: In
          values:
            - enabled