# permissions for end users to view capoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capoconfig-viewer-role
rules:
- apiGroups:
  - config.capo
  resources:
  - capoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.capo
  resources:
  - capoconfigs/status
  verbs:
  - get
