apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "capo.fullname" . }}-leader-election-rolebinding
  namespace: {{ template "capo.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "capo.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "capo.fullname" . }}
    namespace: {{ template "capo.namespace" . }}