apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "capo.fullname" . }}-leader-election-role
  namespace: {{ template "capo.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch