apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "capo.selectorLabels" . | nindent 4 }}
  name: {{ include "capo.fullname" . }}-metrics-service
  namespace: {{ template "capo.namespace" . }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "capo.selectorLabels" . | nindent 4 }}