apiVersion: v1
kind: Service
metadata:
  name: {{ include "capo.fullname" . }}-webhook-service
  namespace: {{ template "capo.namespace" . }}
  labels:
    {{- include "capo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: http
  selector:
    {{- include "capo.selectorLabels" . | nindent 4 }}