apiVersion: v2
name: capo
description: A Helm chart for Kubernetes Calico CNI IP Reserve  

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.1"

icon: https://github.com/xdfdotcn/capo/raw/main/img/logo.png
keywords:
  - kubernetes
  - cni
  - ip reserve
  - validating webhook
sources:
  - https://github.com/xdfdotcn/capo
maintainers:
  - name: xdfdotcn
    url: https://github.com/xdfdotcn
kubeVersion: ">=1.18.0-0"
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://capo.io/docs
  # valid kinds are: added, changed, deprecated, removed, fixed and security
  artifacthub.io/changes: |
    - kind: added
      description: Support for artifacthub.io/changes annotation
    - kind: added
      description: Allow defining imagePullSecrets
    - kind: fixed
      description: Replica count handling
